# Generated by Django 3.1.3 on 2020-11-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201112_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_file',
            new_name='image',
        ),
    ]
